/* 
 * File:   m2mp_client_types.h
 * Author: florent
 *
 * Created on 26 January 2011, 22:32
 */

#ifndef M2MP_CLIENT_TYPES_H
#define	M2MP_CLIENT_TYPES_H

#include <stddef.h>

#ifdef	__cplusplus
extern "C" {
#endif

	/**
	 * M2MP client state
	 */
	typedef enum en_m2mp_client_state {
		/** Not connected */
		M2MP_CLIENT_STATE_NOT_CONNECTED,
		/** Connected */
		M2MP_CLIENT_STATE_CONNECTED,
		/** Identification sent */
		M2MP_CLIENT_STATE_IDENTIFICATION_SENT,
		/** Identified */
		M2MP_CLIENT_STATE_IDENTIFIED
	} m2mp_client_state;

	/**
	 * M2MP client event types
	 */
	typedef enum en_m2mp_client_event_type {
		/** Disconnected */
		M2MP_CLIENT_EVENT_DISCONNECTED,
		/** Connected */
		M2MP_CLIENT_EVENT_CONNECTED,
		/** Identified response received */
		M2MP_CLIENT_EVENT_IDENTIFIED_RESPONSE,
		/** Acknowledge request received */
		M2MP_CLIENT_EVENT_ACK_REQUEST,
		/** Acknowledge response received */
		M2MP_CLIENT_EVENT_ACK_RESPONSE,
		/** Data received */
		M2MP_CLIENT_EVENT_DATA,
		/** Data array received */
		M2MP_CLIENT_EVENT_DATAARRAY,
		/** Other events */
		M2MP_CLIENT_EVENT_PLUGINS
	} m2mp_client_event_type;

	/** Event generated by the m2mp_client library (base type for all the other event types) */
	typedef struct st_m2mp_client_event {
		/** Type of the event */
		m2mp_client_event_type type;
	} m2mp_client_event;

	/** Result of the identification */
	typedef struct st_m2mp_client_event_identified {
		/** Base structure */
		m2mp_client_event base;

		/** Status */
		unsigned char status;
	} m2mp_client_event_identified;

	/** Ack request */
	typedef struct st_m2mp_client_event_ack_request {
		/** Base structure */
		m2mp_client_event base;

		/** Acnknowledge request number */
		unsigned char ackNb;
	} m2mp_client_event_ack_request;

	/** Ack response */
	typedef struct st_m2mp_client_event_ack_response {
		/** Base structure */
		m2mp_client_event base;

		/** Acknowledge response number */
		unsigned char ackNb;
	} m2mp_client_event_ack_response;

	/** Data received */
	typedef struct st_m2mp_client_event_data {
		/** Base structure */
		m2mp_client_event base;

		/** Channel name */
		char * channelName;

		/** Data */
		unsigned char * data;

		/** Length of the data */
		size_t length;
	} m2mp_client_event_data;

	/** Data array received */
	typedef struct st_m2mp_client_event_data_array {
		/** Base structure */
		m2mp_client_event base;

		/** Channel name */
		char * channelName;

		/** Array of data */
		unsigned char ** data;

		/** Size of each data */
		size_t *lengths;

		/** Size of the sizes of data */
		size_t size;
	} m2mp_client_event_dataarray;

	/** Connected to the server event */
	typedef struct st_m2mp_client_event_connected {
		/** Base structure */
		m2mp_client_event base;

		/** Server hostname */
		char * serverHostname;

		/** Server port */
		int serverPort;
	} m2mp_client_event_connected;

	/** Disconnected from the server */
	typedef struct st_m2mp_client_event_disconnected {
		/** Base structure */
		m2mp_client_event base;
	} m2mp_client_event_disconnected;


#ifdef	__cplusplus
}
#endif

#endif	/* M2MP_CLIENT_TYPES_H */

